"""
main.py
-------
Phase 7 (rebuilt): FastAPI backend for the Sri Lanka Tourism Multimodal
RAG system.

This replaces the old setup where Streamlit called generate_response.py
directly (frontend and backend logic living in the same process). Now
Streamlit — or any other client — talks to this API over HTTP, which is
what lets the two be developed, run, and (in the next phase) containerized
independently.

Run from the project root:
    uv run uvicorn backend.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI) once running:
    http://localhost:8000/docs
"""

import tempfile
from pathlib import Path

from fastapi import FastAPI, Form, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware

from backend.config import settings
from backend.generate_response import answer_query

app = FastAPI(
    title="Sri Lanka Tourism RAG API",
    description="Structured (SQL) + semantic (text) + image retrieval, "
    "combined and passed to an LLM for a grounded answer.",
    version="1.0.0",
)

# Wide open for local dev so the Streamlit frontend (a different port/process)
# can call this freely. Tighten allow_origins before deploying anywhere public.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/api/health")
def health():
    """Quick check that the API is up and which LLM provider it's using."""
    return {"status": "ok", "llm_provider": settings.llm_provider}


@app.post("/api/query")
async def query(
    query: str = Form(...),
    image: UploadFile | None = File(None),
):
    """
    Main endpoint: takes a natural-language question and an optional
    uploaded image, runs it through the router -> retrieval -> LLM
    pipeline, and returns the answer plus the raw retrieved context
    (useful for the frontend to show "how this was retrieved").
    """
    image_path = None
    if image is not None:
        suffix = Path(image.filename).suffix
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
        tmp.write(await image.read())
        tmp.close()
        image_path = tmp.name

    try:
        result = answer_query(query, uploaded_image_path=image_path)
    finally:
        # Clean up the temp upload regardless of success/failure
        if image_path:
            Path(image_path).unlink(missing_ok=True)

    return result
